site_name: GRaaS Documentation
theme:
  name: material
nav:
  - About:
    - Intro to GRaaS: "README.md"
    - Attribution: "attribution.md"
  - Developer setup:
    - Setting up a new instance of GRaaS: "new-instance-setup.md"
    - Agency Onboarding Runbook: "server/onboarding-runbook.md"
  - GRaaS hardware intro and assembly: "hardware/README.md"

