site_name: GRaaS Documentation
theme:
  name: material
plugins:
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append('server/app-engine')
                selection:
                    new_path_syntax: true
        watch:
            - server/app-engine

nav:
  - About:
    - Intro to GRaaS: "README.md"
    - Attribution: "attribution.md"
  - Developer setup:
    - Setting up a new instance of GRaaS: "new-instance-setup.md"
    - Agency Onboarding Runbook: "server/onboarding-runbook.md"
  - GRaaS hardware intro and assembly: "hardware/README.md"
  - Testing:
    - Trip Inference: "testing/trip-inference.md"
  - Python docs: "python-docs.md"
