site_name: GRaaS Documentation
theme:
  name: material
nav:
  - Introduction: "index.md"
  - General Transit Feed Utilities: "gtfu/README.md"
  - Runbook: "server/onboarding-runbook.md"
  - Server: "server/README.md"
  - Hardware: "hardware/README.md"
  - Attribution: "attribution.md"
