name: Daily Static GTFS Processes
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        working-directory: gtfu
        run: ./gradlew build
      - name: Update Trip Names
        working-directory: gtfu
        run: java -cp build/libs/gtfu.jar gtfu.tools.TripListGenerator -a glendora-transportation-division
        env:
          GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
