name: Daily Static GTFS Processes
on: [push]
  # Daily at 10PM pacific
  # schedule:
  #   - cron: '0 5 * * *'
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        working-directory: gtfu
        run: ./gradlew build
      - name: Setup Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          # Google recommends using a Workload Identify Federation instead of using the service account key json file
          # but this method is continuing to be supported. More info: https://github.com/google-github-actions/auth#setup
          service_account: 'lat-long-prototype@appspot.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.1.0'
      - name: Install node packages
        working-directory: server/node/
        run: npm install
      - name: Load agency data
        working-directory: gtfu
        run: java -cp build/classes/java/test:build/libs/gtfu.jar gtfu.test.LoadAgencyDataTest -c src/main/resources/conf/cache -u ${{ secrets.LIVE_AGENCIES_URL }}
        env:
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
      - name: Update Trip Names
        working-directory: gtfu
        run: java -cp build/libs/gtfu.jar gtfu.tools.UpdateTripNames -u ${{ secrets.LIVE_AGENCIES_URL }}
        env:
          GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
      - name: Generate Block Data
        working-directory: gtfu
        run: java -cp build/libs/gtfu.jar gtfu.tools.BulkBlockDataGenerator -u ${{ secrets.LIVE_AGENCIES_URL }} -d 2
        env:
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
      - name: Generate Test Block Data
        working-directory: gtfu
        run: |
          java -cp build/libs/gtfu.jar gtfu.tools.BlockDataGenerator -a test -d 0 -U https://unitrans.ucdavis.edu/media/gtfs/Unitrans_GTFS.zip -u
          java -cp build/libs/gtfu.jar gtfu.tools.BlockDataGenerator -a test -d 1 -U https://unitrans.ucdavis.edu/media/gtfs/Unitrans_GTFS.zip -u
          java -cp build/libs/gtfu.jar gtfu.tools.BlockDataGenerator -a test -d 2 -U https://unitrans.ucdavis.edu/media/gtfs/Unitrans_GTFS.zip -u
      - name: Get Unitrans block assignments
        working-directory: server/tests/
        run: NODE_PATH=../node/node_modules node get-block-assignments.js -a unitrans -e UNITRANS_ID_ECDSA -u https://lat-long-prototype.wl.r.appspot.com
        id: unitrans-get-block-assignments
        env:
          UNITRANS_ID_ECDSA: ${{ secrets.UNITRANS_ID_ECDSA }}
      - name: Send Unitrans output
        working-directory: gtfu
        run: java -cp build/libs/gtfu.jar gtfu.tools.SendGrid -r scott.owades@dot.ca.gov -s "Unitrans Block Output" -b steps.unitrans-get-block-assignments.outputs.*
        env:
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
      - name: Get Clean Air Express block assignments
        working-directory: server/tests/
        run: NODE_PATH=../node/node_modules node get-block-assignments.js -a clean-air-express -e CLEAN_AIR_EXPRESS_ID_ECDSA -u https://lat-long-prototype.wl.r.appspot.com
        env:
          CLEAN_AIR_EXPRESS_ID_ECDSA: ${{ secrets.CLEAN_AIR_EXPRESS_ID_ECDSA }}