name: Collect daily GRaaS bot stats
on:
  # Daily at 11PM pacific
  schedule:
    - cron: '0 6 * * *'
jobs:
  Run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '16.1.0'
      - name: Setup Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          # Google recommends using a Workload Identify Federation instead of using the service account key json file
          # but this method is continuing to be supported. More info: https://github.com/google-github-actions/auth#setup
          service_account: 'lat-long-prototype@appspot.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Run Python unit tests
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - run: |
          pip install -r server/app-engine/requirements.txt
          python server/app-engine/graas_bot.py
        env:
          GRAAS_BOT_WEBHOOK: ${{ secrets.GRAAS_BOT_WEBHOOK }}
