name: PR Test
on: [pull_request]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '16.1.0'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          node-version: '16.1.0'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        with:
          node-version: '16.1.0'
      - name: Build with Gradle (incl unit tests)
        working-directory: gtfu
        run: ./gradlew build
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.1.0'
      - name: Setup Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          # Google recommends using a Workload Identify Federation instead of using the service account key json file
          # but this method is continuing to be supported. More info: https://github.com/google-github-actions/auth#setup
          service_account: 'lat-long-prototype@appspot.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
      - name: Install node packages
        working-directory: server/node/
        run: npm install
      - name: Run position update script
        working-directory: server/tests/
        run: NODE_PATH=../node/node_modules node test-position-update.js -u https://lat-long-prototype.wl.r.appspot.com -a pr-test -e PR_TEST_ID_ECDSA
        env:
          PR_TEST_ID_ECDSA: ${{ secrets.PR_TEST_ID_ECDSA }}
      - name: Run service alert script
        working-directory: server/tests/
        run: NODE_PATH=../node/node_modules node post-service-alerts.js -u https://lat-long-prototype.wl.r.appspot.com -a pr-test -e PR_TEST_ID_ECDSA
        env:
          PR_TEST_ID_ECDSA: ${{ secrets.PR_TEST_ID_ECDSA }}
      - name: Run trip updates script
        working-directory: server/tests/
        run: NODE_PATH=../node/node_modules node post-stop-time-entities.js -u https://lat-long-prototype.wl.r.appspot.com -a pr-test -e PR_TEST_ID_ECDSA
        env:
          PR_TEST_ID_ECDSA: ${{ secrets.PR_TEST_ID_ECDSA }}
      - name: Run eslint
        working-directory: server/tools/eslint/
        run: ./lint-files.sh
      - name: Run Python unit tests
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - run: |
          pip install -r server/app-engine/requirements.txt
          python server/tests/unit-tests.py
