name: Send GRaaS Report
# ~9:18PM pacific time, daily:
on: [push]
 # schedule:
 #    - cron: '0 5 * * *'
jobs:
  Send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account: 'lat-long-prototype@appspot.gserviceaccount.com'
          credentials_json: {{ fromJson(secrets.GCP_SA_KEY_JSON) }}
          export_default_credentials: true
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        working-directory: gtfu
        run: ./gradlew build
      - name: Run SendGrid Script
        working-directory: gtfu
        env:
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
        run: java -cp build/libs/gtfu.jar gtfu.GraphicReport  -c src/main/resources/conf/cache


